-- Base da migracao DB-first de faturas.
-- O usuario aplicou a parte estrutural diretamente no DataGrip em 2026-09-19.
-- Este arquivo registra a estrutura para que uma instalacao nova nao dependa de memoria.

create table if not exists public.faturas (
  id bigint generated by default as identity primary key,
  referencia date not null unique,
  vencimento date not null,
  pago boolean not null default false,
  constraint faturas_referencia_primeiro_dia
    check (referencia = date_trunc('month', referencia)::date)
);

alter table public.lancamentos
  add column if not exists fatura_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'lancamentos_fatura_id_fkey'
      and conrelid = 'public.lancamentos'::regclass
  ) then
    alter table public.lancamentos
      add constraint lancamentos_fatura_id_fkey
      foreign key (fatura_id)
      references public.faturas (id)
      on update cascade
      on delete restrict;
  end if;
end $$;

create index if not exists lancamentos_fatura_id_idx
  on public.lancamentos (fatura_id);

-- A aplicacao so precisa LER faturas: criacao, alteracao e exclusao ficam no DataGrip.
-- Deve ser aplicada somente apos a aprovacao explicita da politica RLS.
alter table public.faturas enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'faturas'
      and policyname = 'faturas leitura logada'
  ) then
    create policy "faturas leitura logada"
      on public.faturas
      for select
      to authenticated
      using (true);
  end if;
end $$;
