<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Vcl.FinHub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Vcl.FinHub.Domain\Vcl.FinHub.Domain.csproj" />
    <ProjectReference Include="..\Vcl.FinHub.TestBase\Vcl.FinHub.TestBase.csproj" />
  </ItemGroup>

</Project>
