<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Vcl.FinHub</RootNamespace>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
    <UserSecretsId>Vcl.FinHub-4681b4fd-151f-4221-84a4-929d86723e4c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" Version="10.6.1" />
    <PackageReference Include="Volo.Abp.Autofac" Version="10.6.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="10.6.1" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="10.6.1" />
    <PackageReference Include="Volo.Abp.Account.Web.OpenIddict" Version="10.6.1" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" Version="10.6.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vcl.FinHub.Application\Vcl.FinHub.Application.csproj" />
    <ProjectReference Include="..\Vcl.FinHub.EntityFrameworkCore\Vcl.FinHub.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Vcl.FinHub.HttpApi\Vcl.FinHub.HttpApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

</Project>
